In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

data=pd.read_csv('/content/drive/MyDrive/Tableau_IMDB_Project/TMDB  IMDB Movies Dataset.csv')

In [ ]:
data

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,genres,production_companies,production_countries,spoken_languages,keywords,directors,writers,averageRating,numVotes,cast
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",Christopher Nolan,Christopher Nolan,8.8,2670355,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",Christopher Nolan,"Jonathan Nolan, Christopher Nolan",8.7,2326479,"Matthew McConaughey, Anne Hathaway, Michael Ca..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Go...",9.0,3005759,"Christian Bale, Heath Ledger, Aaron Eckhart, M..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",James Cameron,James Cameron,7.9,1426722,"Sam Worthington, Zoe Saldaña, Sigourney Weaver..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",Joss Whedon,"Joss Whedon, Zak Penn",8.0,1502823,"Robert Downey Jr., Chris Evans, Mark Ruffalo, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433600,765928,Ali Kathawa,0.000,0,Released,2017-05-18,0,0,False,/iWWknnn3loEQKAQfE7FpPQTUypV.jpg,...,NaN,NaN,NaN,Sinhalese,NaN,Sunil Ariyaratne,"Sunil Ariyaratne, Letitia Botejue",6.3,30,"Giriraj Kaushalya, Wilson Gunaratne, Kumara Th..."
433601,765866,Cost You Nothing,0.000,0,Released,2020-11-13,0,10,False,NaN,...,NaN,NaN,NaN,NaN,NaN,Patricia Kelly,Patricia Kelly,4.8,5,NaN
433602,765868,Der 90. Geburtstag,0.000,0,Released,2012-02-15,0,7,False,NaN,...,Animation,NaN,NaN,"German, No Language",NaN,Thomas Scherer,Thomas Scherer,5.6,14,NaN
433603,765873,Miracle On 34th Street,0.000,0,Released,1959-11-27,0,60,False,NaN,...,"Family, Drama",Talent Associates,United States of America,NaN,NaN,William Corrigan,"Valentine Davies, George Seaton, Harry Miles M...",6.9,172,"Ed Wynn, Peter Lind Hayes, Mary Healy, Orson B..."
433604,765888,Next,0.000,0,Released,2017-06-07,0,15,False,NaN,...,Drama,NaN,Brazil,Portuguese,NaN,Luiza Campos,Maya Guizzo,8.5,12,"Amanda Delbone, Nina Medeiros, Antoniela Canto..."

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 433605 entries, 0 to 433604
Data columns (total 29 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    433605 non-null  int64
 1   title                 433605 non-null  object
 2   vote_average          433605 non-null  float64
 3   vote_count            433605 non-null  int64
 4   status                433605 non-null  object
 5   release_date          414971 non-null  object
 6   revenue               433605 non-null  int64
 7   runtime               433605 non-null  int64
 8   adult                 433605 non-null  bool
 9   backdrop_path         183999 non-null  object
 10  budget                433605 non-null  int64
 11  homepage              54247 non-null   object
 12  tconst                433605 non-null  object
 13  original_language     433605 non-null  object
 14  original_title        433605 non-null  object
 15  overview              392006 non-null  object
 16  popularity            433605 non-null  float64
 17  poster_path           359048 non-null  object
 18  tagline               91206 non-null   object
 19  genres                355884 non-null  object
 20  production_companies  262212 non-null  object
 21  production_countries  321482 non-null  object
 22  spoken_languages      331735 non-null  object
 23  keywords              170691 non-null  object
 24  directors             423315 non-null  object
 25  writers               366948 non-null  object
 26  averageRating         433605 non-null  float64
 27  numVotes              433605 non-null  int64
 28  cast                  365122 non-null  object
dtypes: bool(1), float64(3), int64(6), object(19)
memory usage: 93.0+ MB

In [ ]:
# Dropping of columns that are not required- status, backdrop_path, homepage, tconst, original_title, overview, poster_path, tagline

data1= data.drop(['status', 'backdrop_path', 'homepage', 'tconst', 'original_title', 'overview', 'poster_path', 'tagline'], axis=1)

data1

,id,title,vote_average,vote_count,release_date,revenue,runtime,adult,budget,original_language,...,genres,production_companies,production_countries,spoken_languages,keywords,directors,writers,averageRating,numVotes,cast
0,27205,Inception,8.364,34495,2010-07-15,825532764,148,False,160000000,en,...,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",Christopher Nolan,Christopher Nolan,8.8,2670355,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W..."
1,157336,Interstellar,8.417,32571,2014-11-05,701729206,169,False,165000000,en,...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",Christopher Nolan,"Jonathan Nolan, Christopher Nolan",8.7,2326479,"Matthew McConaughey, Anne Hathaway, Michael Ca..."
2,155,The Dark Knight,8.512,30619,2008-07-16,1004558444,152,False,185000000,en,...,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Go...",9.0,3005759,"Christian Bale, Heath Ledger, Aaron Eckhart, M..."
3,19995,Avatar,7.573,29815,2009-12-15,2923706026,162,False,237000000,en,...,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",James Cameron,James Cameron,7.9,1426722,"Sam Worthington, Zoe Saldaña, Sigourney Weaver..."
4,24428,The Avengers,7.710,29166,2012-04-25,1518815515,143,False,220000000,en,...,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",Joss Whedon,"Joss Whedon, Zak Penn",8.0,1502823,"Robert Downey Jr., Chris Evans, Mark Ruffalo, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433600,765928,Ali Kathawa,0.000,0,2017-05-18,0,0,False,0,si,...,NaN,NaN,NaN,Sinhalese,NaN,Sunil Ariyaratne,"Sunil Ariyaratne, Letitia Botejue",6.3,30,"Giriraj Kaushalya, Wilson Gunaratne, Kumara Th..."
433601,765866,Cost You Nothing,0.000,0,2020-11-13,0,10,False,0,en,...,NaN,NaN,NaN,NaN,NaN,Patricia Kelly,Patricia Kelly,4.8,5,NaN
433602,765868,Der 90. Geburtstag,0.000,0,2012-02-15,0,7,False,0,en,...,Animation,NaN,NaN,"German, No Language",NaN,Thomas Scherer,Thomas Scherer,5.6,14,NaN
433603,765873,Miracle On 34th Street,0.000,0,1959-11-27,0,60,False,0,en,...,"Family, Drama",Talent Associates,United States of America,NaN,NaN,William Corrigan,"Valentine Davies, George Seaton, Harry Miles M...",6.9,172,"Ed Wynn, Peter Lind Hayes, Mary Healy, Orson B..."
433604,765888,Next,0.000,0,2017-06-07,0,15,False,0,pt,...,Drama,NaN,Brazil,Portuguese,NaN,Luiza Campos,Maya Guizzo,8.5,12,"Amanda Delbone, Nina Medeiros, Antoniela Canto..."

In [ ]:
# Converting release_date dtype from object to datetime

data1['release_date']=pd.to_datetime(data1['release_date'], errors='coerce')

<ipython-input-10-d4ff5f9f4e1f>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['release_date']=pd.to_datetime(data1['release_date'], errors='coerce')

In [ ]:
# Since the dataset is very large and has movies from 19th century as well, so lets filter out them to include movies having release year from 2000

data1= data1[data1['release_date'].dt.year>=2000]

In [ ]:
# Lets include movies having original language english

data2= data1[data1['original_language']=='en']

In [ ]:
data2

,id,title,vote_average,vote_count,release_date,revenue,runtime,adult,budget,original_language,...,genres,production_companies,production_countries,spoken_languages,keywords,directors,writers,averageRating,numVotes,cast
0,27205,Inception,8.364,34495,2010-07-15,825532764,148,False,160000000,en,...,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",Christopher Nolan,Christopher Nolan,8.8,2670355,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W..."
1,157336,Interstellar,8.417,32571,2014-11-05,701729206,169,False,165000000,en,...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",Christopher Nolan,"Jonathan Nolan, Christopher Nolan",8.7,2326479,"Matthew McConaughey, Anne Hathaway, Michael Ca..."
2,155,The Dark Knight,8.512,30619,2008-07-16,1004558444,152,False,185000000,en,...,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Go...",9.0,3005759,"Christian Bale, Heath Ledger, Aaron Eckhart, M..."
3,19995,Avatar,7.573,29815,2009-12-15,2923706026,162,False,237000000,en,...,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",James Cameron,James Cameron,7.9,1426722,"Sam Worthington, Zoe Saldaña, Sigourney Weaver..."
4,24428,The Avengers,7.710,29166,2012-04-25,1518815515,143,False,220000000,en,...,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",Joss Whedon,"Joss Whedon, Zak Penn",8.0,1502823,"Robert Downey Jr., Chris Evans, Mark Ruffalo, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433597,765911,Rope.,0.000,0,2017-01-01,0,49,False,0,en,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.6,5,Lilith
433598,765918,Mexican Wave,0.000,0,2018-11-18,0,61,False,0,en,...,Documentary,NaN,NaN,English,NaN,Judson Vaughan,"Marisa Polin, Judson Vaughan",9.2,20,NaN
433599,765926,Out of Time,0.000,0,2020-11-18,0,73,False,0,en,...,Drama,NaN,NaN,English,NaN,Leon Lopez,Kerry Williams,5.5,92,NaN
433601,765866,Cost You Nothing,0.000,0,2020-11-13,0,10,False,0,en,...,NaN,NaN,NaN,NaN,NaN,Patricia Kelly,Patricia Kelly,4.8,5,NaN
433602,765868,Der 90. Geburtstag,0.000,0,2012-02-15,0,7,False,0,en,...,Animation,NaN,NaN,"German, No Language",NaN,Thomas Scherer,Thomas Scherer,5.6,14,NaN

In [ ]:
# we will consider movies which are available for all age groups

data3= data2[data2['adult']==False]

In [ ]:
# sorting genre values of each row in alphabetical order to prevent it from duplication

def clean_genre(genres):
    if isinstance(genres, str):
      genre_list= genres.split(',')
      clean_list=[]
      for g in genre_list:
        clean_list.append(g.strip())
      clean_list.sort()
      return ' ,'.join(clean_list)

    else:
      return ''

new_column=[]
for value in data3['genres']:
    new_column.append(clean_genre(value))

data3['genres']=new_column

<ipython-input-14-170453ab85bd>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data3['genres']=new_column

In [ ]:
data3

,id,title,vote_average,vote_count,release_date,revenue,runtime,adult,budget,original_language,...,genres,production_companies,production_countries,spoken_languages,keywords,directors,writers,averageRating,numVotes,cast
0,27205,Inception,8.364,34495,2010-07-15,825532764,148,False,160000000,en,...,"Action ,Adventure ,Science Fiction","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",Christopher Nolan,Christopher Nolan,8.8,2670355,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W..."
1,157336,Interstellar,8.417,32571,2014-11-05,701729206,169,False,165000000,en,...,"Adventure ,Drama ,Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",Christopher Nolan,"Jonathan Nolan, Christopher Nolan",8.7,2326479,"Matthew McConaughey, Anne Hathaway, Michael Ca..."
2,155,The Dark Knight,8.512,30619,2008-07-16,1004558444,152,False,185000000,en,...,"Action ,Crime ,Drama ,Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Go...",9.0,3005759,"Christian Bale, Heath Ledger, Aaron Eckhart, M..."
3,19995,Avatar,7.573,29815,2009-12-15,2923706026,162,False,237000000,en,...,"Action ,Adventure ,Fantasy ,Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",James Cameron,James Cameron,7.9,1426722,"Sam Worthington, Zoe Saldaña, Sigourney Weaver..."
4,24428,The Avengers,7.710,29166,2012-04-25,1518815515,143,False,220000000,en,...,"Action ,Adventure ,Science Fiction",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",Joss Whedon,"Joss Whedon, Zak Penn",8.0,1502823,"Robert Downey Jr., Chris Evans, Mark Ruffalo, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433597,765911,Rope.,0.000,0,2017-01-01,0,49,False,0,en,...,,NaN,NaN,NaN,NaN,NaN,NaN,7.6,5,Lilith
433598,765918,Mexican Wave,0.000,0,2018-11-18,0,61,False,0,en,...,Documentary,NaN,NaN,English,NaN,Judson Vaughan,"Marisa Polin, Judson Vaughan",9.2,20,NaN
433599,765926,Out of Time,0.000,0,2020-11-18,0,73,False,0,en,...,Drama,NaN,NaN,English,NaN,Leon Lopez,Kerry Williams,5.5,92,NaN
433601,765866,Cost You Nothing,0.000,0,2020-11-13,0,10,False,0,en,...,,NaN,NaN,NaN,NaN,Patricia Kelly,Patricia Kelly,4.8,5,NaN
433602,765868,Der 90. Geburtstag,0.000,0,2012-02-15,0,7,False,0,en,...,Animation,NaN,NaN,"German, No Language",NaN,Thomas Scherer,Thomas Scherer,5.6,14,NaN

In [ ]:
# Saving the cleaned file

data3.to_csv('/content/drive/MyDrive/Tableau_IMDB_Project/TMDB+IMDB_New_Data.csv')